TrajectoryPlannerROS:

  holonomic_robot: false
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.5
  sim_time: 1.5
  pdist_scale: 0.8
  gdist_scale: 0.4
  meter_scoring: true
  angular_sim_granularity: 0.01
  acc_lim_x: 20.0
  acc_lim_y: 20.0
