TrajectoryPlannerROS:

  max_vel_x: 2.0
  min_vel_x: 1.0
  max_vel_y: 2.0
  min_vel_y: 1.0
  max_vel_y: 1.5
  min_vel_y: -1.5 
  holonomic_robot: false
  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.5
  sim_time: 2.0
  pdist_scale: 0.4
  meter_scoring: true
  
