TrajectoryPlannerROS:

  holonomic_robot: false
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.5
  sim_time: 1.5
  pdist_scale: 0.8
  gdist_scale: 0.4
  meter_scoring: true
  angular_sim_granularity: 0.01
