map_type: costmap

obstacle_range: 9.0
raytrace_range: 10.0

transform_tolerance: 1.0

#footprint: [[0.3, 0.3], [-0.3, 0.3], [-0.3, -0.3], [0.3, -0.3]]
robot_radius: 0.25 
cost_scaling_factor: 20.0

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}


#map_type: costmap

#obstacle_range: 0.0
#raytrace_range: 0.0

#transform_tolerance: 0.0

#robot_radius: 0.0 
#inflation_radius: 0.0

#observation_sources: laser_scan_sensor

#laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}

